/** @format */

import React, { useState, useEffect } from 'react';
import Odometer from 'react-odometerjs';
import 'odometer/themes/odometer-theme-default.css';
import './Home.css';
import brand_logo from '../../Assets/Shiv_Paradise_Logo.png';
import Carousel from 'react-multi-carousel';
import 'react-multi-carousel/lib/styles.css';
import { home_carousel } from './data';

const Home = () => {
  const [value, setValue] = useState({
    first: 0,
    second: 0,
    third: 0,
    fourth: 0,
    fifth: 0,
    sixth: 0,
  });
  const handleScroll = () => {
    const position = window.pageYOffset;
    if (position > 100) {
      setValue({
        first: 100,
        second: 7,
        third: 800,
        fourth: 1.5,
        fifth: 1000,
        sixth: 150,
      });
    }
  };
  useEffect(() => {
    window.addEventListener('scroll', handleScroll, { passive: true });
    return () => {
      window.removeEventListener('scroll', handleScroll);
    };
  }, []);
  const responsive = {
    superLargeDesktop: {
      // the naming can be any, depends on you.
      breakpoint: { max: 4000, min: 3000 },
      items: 5,
    },
    desktop: {
      breakpoint: { max: 3000, min: 1024 },
      items: 1,
    },
    tablet: {
      breakpoint: { max: 1024, min: 464 },
      items: 2,
    },
    mobile: {
      breakpoint: { max: 464, min: 0 },
      items: 1,
    },
  };
  return (
    <section>
      <div className='banner-sec fluid-container'>
        <img src={require('../../Assets/home banner_image.png')} alt='' />
      </div>
      <div className='banner-tag'>
        <div className='row'>
          <div className='col'>
            <div className='tags animated fadeInLeft'>
              <img src={brand_logo} alt='' width='300px' />
              <h2 className='pt-3 pb-3'>Experiance The Paradise life</h2>
              <button className='tag-button'> Explore Now</button>
            </div>
          </div>
        </div>
      </div>
      <div>
        <div className='funfacts-inner'>
          <div className='row p-3 m-auto'>
            <div className='col-lg-4 col-6 col-sm-6'>
              <div className='animated fadeInLeft'>
                <div className='single-funfacts'>
                  <div className='funfacts-style-two'>
                    <h3>
                      <Odometer format='d' value={value.first} />+
                    </h3>
                    <p>Total Startups supported</p>
                  </div>
                </div>
              </div>
            </div>
            <div className='col-lg-4 col-6 col-sm-6'>
              <div className='animated fadeInLeft'>
                <div className='single-funfacts'>
                  <div className='funfacts-style-two'>
                    <h3>
                      <Odometer format='(,ddd).dd' value={value.second} /> Cr+
                    </h3>
                    <p>Total funds sanctioned to Startups</p>
                  </div>
                </div>
              </div>
            </div>

            <div className='col-lg-4 col-6 col-sm-6'>
              <div className='animated fadeInLeft'>
                <div className='single-funfacts'>
                  <div className='funfacts-style-two'>
                    <h3>
                      <Odometer
                        format='(,ddd).dd'
                        duration={2000}
                        value={value.third}
                      />{' '}
                      Cr+
                    </h3>
                    <p>Total revenues generated by Startups</p>
                  </div>
                </div>
              </div>
            </div>

            <div className='col-lg-4 col-6 col-sm-6'>
              <div className='animated fadeInLeft'>
                <div className='single-funfacts'>
                  <div className='funfacts-style-two'>
                    <h3>
                      <Odometer
                        format='(,ddd).dd'
                        duration={2000}
                        value={value.fourth}
                      />{' '}
                      Lac <span className='fs-4'>Sq.ft</span>
                    </h3>
                    <p>Dedicated Incubation Space</p>
                  </div>
                </div>
              </div>
            </div>

            <div className='col-lg-4 col-6 col-sm-6'>
              <div className='animated fadeInLeft'>
                <div className='single-funfacts'>
                  <div className='funfacts-style-two'>
                    <h3>
                      <Odometer
                        format='(,ddd).dd'
                        duration={2000}
                        value={value.fifth}
                      />
                      +
                    </h3>
                    <p>Total jobs created by Startups</p>
                  </div>
                </div>
              </div>
            </div>
            <div className='col-lg-4 col-6 col-sm-6'>
              <div className='animated fadeInLeft'>
                <div className='single-funfacts'>
                  <div className='funfacts-style-two'>
                    <h3>
                      <Odometer format='(,ddd).dd' value={value.sixth} />+
                    </h3>
                    <p>Mentors Associated</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div className='container carousel'>
        <h4 className='text-center m-3 head-title'>Our Completed Projects</h4>
        <Carousel
          responsive={responsive}
          swipeable={true}
          draggable={true}
          slidesToSlide={1}
          showDots={true}
          ssr={true}
          infinite={true}
          autoPlay={true}
          autoPlaySpeed={5000}
          rewind={true}
          renderDotsOutside={true}
          keyBoardControl={false}
          centerMode={true}
          removeArrowOnDeviceType={['tablet', 'mobile']}
          dotListClass='custom-dot-list-style'>
          {home_carousel.map((item, index) => (
            <div className='card' key={index}>
              <div className='img-card'>
                <img src={item.images} alt='' />
              </div>
              <div className='testimonial mt-4 mb-4 text-center'>
                Lorem ipsum dolor sit amet consectetur adipisicing elit.
                Accusamus expedita dicta doloremque odit saepe quo natus aut
                accusantium alias blanditiis.
              </div>
              <div className='name'>{item.name}</div>
            </div>
          ))}
        </Carousel>
      </div>
      <div>
        <div className='banner-sec1'>
          <img
            src={require('../../Assets/About us.png')}
            alt='About-us'
            width='100%'
            height='auto'
          />

          <img
            className='shiv_logo'
            src={require('../../Assets/Shiv Logo.png')}
            alt=''
          />
          <p className='Shiv_tag'>
            Great Things Never Come <br /> From Comfort Zones
          </p>
          <button className='tag-button shiv-btn'>About Us</button>
        </div>
      </div>
    </section>
  );
};

export default Home;

// document.querySelector(document).ready(function () {
//
// });
